### ISSUE TITLE
ERROR: ./../folly/portability/Malloc.h:27:12: error: unknown type name 'size_t'

### ISSUE THREAD

**Issue by loretoparisi** [facebook/redex#39] opened 2016-04-13 15:24 UTC
I came out with this error:

```shell
In file included from portability/Malloc.cpp:17:
./../folly/portability/Malloc.h:27:12: error: unknown type name 'size_t'
extern "C" size_t malloc_usable_size(void* ptr);
           ^
1 error generated.
make[4]: *** [portability/Malloc.lo] Error 1
make[3]: *** [all-recursive] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
macbookproloreto:redex admin$ 
```

Reg:
`MacOS X 10.10.5`
`Python 3.5.1`

**Comment by loretoparisi** [comment] 2016-04-13 15:26
It seems to be the same as https://github.com/facebook/redex/issues/8

**Comment by loretoparisi** [comment] 2016-04-13 16:07
So,
I have fixed the `<>` import issue and added the `stddef.h` stdlib 
to `third party/folly/folly/portability/Malloc.h`

```bash
#include "stddef.h"
#include "malloc.h"
```

and this time it compiled!

**Comment by jrodbx** [comment] 2016-04-13 16:59
This appears to be a duplicate of https://github.com/facebook/redex/issues/8

**Comment by bertmaher** [comment] 2016-04-13 17:59
Yep, this is #8 , thanks @jrodbx.

**Closed by bertmaher** 2016-04-13 17:59 UTC
