### ISSUE TITLE
redex does not allow for reproducible builds

### ISSUE THREAD

**Issue by djh82** [facebook/redex#683] opened 2022-03-08 13:35 UTC
When running redex, on the same dex, we continually get different output (the md5 of the output differs), which makes it impossible to use in a reproducible build system.

What is the likely cause of this?  And is there anything we do about it?

**Comment by NTillmann** [comment] 2022-03-10 01:11
We strive for Redex to be deterministic. In fact, that's something we are monitoring ourselves, and fix issues that we find.

Make sure you are using the stable-branch, as it's likely that some non-determinism shows up in the main branch from time to time: https://github.com/facebook/redex/tree/stable

Redex can produce a "redex-stats.txt" via the "stats_output" config arg. It contains various metrics and hashes for all the individual optimization passes that Redex runs. We use that to determine if a particular pass introduces non-determinism. You could compare them locally, and maybe exclude particular offending passes, or post two diverging ones here, ideally with a repro setup, so that we might be able to help with a more detailed diagnosis.

**Comment by djh82** [comment] 2022-03-10 11:11
I have retried with the current stable branch, and still get non-reproducible builds.  The most obvious difference in those stats files you reference (besides the `vm_hwm_*`) are the `method_refs_candidates` and `method_refs_rebound` which are different by 1 or 2 when the output differs.

**Comment by NTillmann** [comment] 2022-03-10 16:31
Right, sorry, I should have mentioned this. The `vm_hwm*` metrics are not meant to be stable. They refer to some internal state of the memory subsystem, telling us something about memory consumption, but they are not guaranteed to be stable. Just ignore those.

The `method_refs_candidates` and `method_refs_rebound` should be stable. We are not observing any non-determinism with those. Are you sure that the external dependencies you are passing into Redex are identical?

**Comment by djh82** [comment] 2022-03-10 16:54
I can run the same command repeatedly (with the same config and DEX, i.e. without recompiling the input) and reliably get 1 of about 4 different outputs with RedbindRefs enabled.

**Comment by djh82** [comment] 2022-03-10 18:36
I assume it has something to do with the parallel walk?  Outputting TRACE logging seems to cause the non-determinism to reduce significantly; setting the number of threads for the walk to 1 has caused the issue to seemingly resolve itself.

**Comment by NTillmann** [comment] 2022-03-10 20:02
I like your approach of digging into the ReBindRefsPass, and looking at the parallel walk in particular.

However, reading through the source code, I couldn't spot any obvious source of non-determinism, and as I said before, we've not observed any non-determinism with the ReBindRefsPass.

Sounds like you might have a work-around for your scenario by disabling the parallel walk, or also possibly just disabling the pass entirely --- it's optional.

It seems that with a little bit more analysis / logging, you might be able to find the root cause. We'd very much appreciate that, and I'd love to incorporate a fix. For us to help, we'd need a way to reproduce the issue.

**Comment by djh82** [comment] 2022-03-11 13:52
Some more investigation has revealed that these are the methods that are sometimes rebound and sometimes are not:

```
Rebinding Lorg/joda/time/chrono/GJChronology$CutoverField;.add:(JI)J=>Lorg/joda/time/DateTimeField;.add:(JI)J
Rebinding Lorg/joda/time/chrono/GJChronology$CutoverField;.get:(J)I=>Lorg/joda/time/DateTimeField;.get:(J)I
Rebinding Lorg/joda/time/chrono/GJChronology$CutoverField;.get:(J)I=>Lorg/joda/time/DateTimeField;.get:(J)I
Rebinding Lorg/joda/time/chrono/GJChronology$CutoverField;.getMaximumValue:(J)I=>Lorg/joda/time/DateTimeField;.getMaximumValue:(J)I
Rebinding Lorg/joda/time/chrono/GJChronology$CutoverField;.getMaximumValue:(J)I=>Lorg/joda/time/DateTimeField;.getMaximumValue:(J)I
```

**Comment by NTillmann** [comment] 2022-03-11 18:59
Haven't tried to repro yet, but looking at the classes involved, seeing that some are non-public, I now see the potential for a race in ReBindRefs.cpp between the call to `set_public(cls);` and the `is_public(curr_cls_vis)` check.

**Comment by NTillmann** [comment] 2022-03-11 21:26
@djh82, can you check if this would solve the problem for you? https://github.com/facebook/redex/pull/684

**Comment by djh82** [comment] 2022-03-13 19:00
Seems to; have run it 100 times without seeing a change in the MD5 :+1:

**Comment by NTillmann** [comment] 2022-03-15 00:18
The change has been merged into the main branch. As it has some potential to cause new issues, we'll let it soak for a while before it may get promoted to the -stable branch.

**Closed by NTillmann** 2022-03-15 00:18 UTC
