### ISSUE TITLE
RuntimeError: redex-all crashed with exit code -9! 

### ISSUE THREAD

**Issue by kayan1990** [facebook/redex#403] opened 2019-05-30 08:05 UTC
Running redex on my app encounters this issue.

redex myapp.apk -o output.apk

Using config (default)
Using binary (default)
Extracting apk...
Detected dex mode Api21DexMode
Unpacking dex files
Detecting Application Modules
Unpacking APK finished in 0.97 seconds
Running redex-all on 4 dex files 
Running redex binary at /tmp/redex.FPycjG/redex-all
Trace settings:
TRACEFILE=
SHOW_TIMESTAMPS=
SHOW_TRACEMODULE=
TRACE_METHOD_FILTER=
Loading classes from dex from /tmp/redex.FPycjG/tmp2h_Pzf.redex_dexen/dex0/classes.dex
Loading classes from dex from /tmp/redex.FPycjG/tmp2h_Pzf.redex_dexen/dex1/classes2.dex
Loading classes from dex from /tmp/redex.FPycjG/tmp2h_Pzf.redex_dexen/dex2/classes3.dex
Loading classes from dex from /tmp/redex.FPycjG/tmp2h_Pzf.redex_dexen/dex3/classes4.dex
Traceback (most recent call last):
  File "/tmp/redex.FPycjG/redex.py", line 785, in <module>
    run_redex(args)
  File "/tmp/redex.FPycjG/redex.py", line 762, in run_redex
    run_redex_binary(state)
  File "/tmp/redex.FPycjG/redex.py", line 224, in run_redex_binary
    'by running %(lldb_script_name)s') % script_filenames)
RuntimeError: redex-all crashed with exit code -9! You can re-run it under gdb by running /tmp/redex.FPycjG/redex-gdb-cAjfd_.sh or under lldb by running /tmp/redex.FPycjG/redex-lldb-_6jMq1.sh

**Comment by thezhangwei** [comment] 2019-05-30 17:19
Do you mind running it under the debugger like this /tmp/redex.FPycjG/redex-gdb-cAjfd_.sh to gather more info about the crash please?

**Comment by kayan1990** [comment] 2019-05-31 07:55
Like this？
redex myapp.apk --gdb
(gdb) run redex myapp.apk -o 1.apk

the out directory  is writable

kayan@kayan-virtual-machine:~/Downloads$ redex myapp.apk --gdb
GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /tmp/redex.Lj177X/redex-all...done.
**(gdb) run redex myapp.apk -o 1.apk**
Starting program: /tmp/redex.Lj177X/redex-all redex myapp.apk -o 1.apk
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
error: outdir is not a writable directory: 1.apk
[Inferior 1 (process 51148) exited with code 01]
(gdb)

**Comment by justinjhendrick** [comment] 2019-05-31 18:36
I think you should pass your arguments to `redex` on the same line that you pass `--gdb`, instead of from within gdb.

`kayan@kayan-virtual-machine:~/Downloads$ redex myapp.apk --gdb`
should instead be
`kayan@kayan-virtual-machine:~/Downloads$ redex myapp.apk --gdb -o 1.apk`

`redex` is actually a python wrapper script that probably turns your relative path `./1.apk` into an absolute path before passing it onto the redex c++ binary (known as `redex-all`) which is in a `/tmp` directory. When you give the arguments within gdb you're probably giving a relative path into that `/tmp` directory which I guess isn't writable by the redex program?

**Comment by kayan1990** [comment] 2019-06-03 02:59
I pass an absolute path，but the result didn't change.

this is my apk download url, can you help me run redex on my apk to see what happened?
[https://apkpure.com/hago/com.yy.hiyo](url)

**kayan@kayan-virtual-machine:~/Downloads$ redex '/home/kayan/Downloads/myapp.apk' --gdb -o '/home/kayan/Downloads/4.apk'**
GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /tmp/redex.tHWj3u/redex-all...done.
**(gdb) run redex '/home/kayan/Downloads/myapp.apk'  -o '/home/kayan/Downloads/4.apk'**
Starting program: /tmp/redex.tHWj3u/redex-all redex '/home/kayan/Downloads/myapp.apk'  -o '/home/kayan/Downloads/4.apk'
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
error: outdir is not a writable directory: /home/kayan/Downloads/4.apk
[Inferior 1 (process 120449) exited with code 01]
(gdb)

**Comment by justinjhendrick** [comment] 2019-06-04 01:01
We've reproduced the error and @helloguo is looking into it. Thanks for the bug report!

**Comment by kayan1990** [comment] 2019-06-04 03:09
Thanks a lot, when the bug is fixed, can you notify me?

**Comment by thezhangwei** [comment] 2019-11-15 21:24
Hi, sorry for the late response. @helloguo mentioned that he couldn't repro the crash with the correct command. Could you please try again? Thanks,

**Comment by thezhangwei** [comment] 2019-11-21 19:06
Closing since the issue seems have been resolved. Let's open another one if it still repros.

**Closed by thezhangwei** 2019-11-21 19:06 UTC
Labels: bug

**Comment by openaphid** [comment] 2020-09-13 02:16
According to the code, it expects the output of `-o` to be a directory, not a file. I think the [official guide](https://fbredex.com/docs/usage) is kinda misleading.

https://github.com/facebook/redex/blob/83e3fab1fd7aa1ca213a44b959adbd2b2a6c20a0/tools/redex-all/main.cpp#L416,
