### ISSUE TITLE
redex input.apk -o output.apk

### ISSUE THREAD

**Issue by DanielDong** [facebook/redex#105] opened 2016-04-19 09:37 UTC
opt/bridge/Bridge.cpp:61: DexMethod *(anonymous namespace)::match_pattern(DexMethod *): assertion `it == end' failed.
In public final bridge rz$1.a(Ljava/lang/Object;)V
0   redex-all                           0x0000000107a7f214 _Z15crash_backtracei + 52
1   libsystem_platform.dylib            0x00007fff9900352a _sigtramp + 26
2   ???                                 0x0000000000000028 0x0 + 40
3   libsystem_c.dylib                   0x00007fff937da6e7 abort + 129
4   redex-all                           0x0000000107a7f1d1 _Z11assert_failPKcS0_jS0_S0_z + 177
5   redex-all                           0x0000000107ae7b40 _ZZN13BridgeRemover12find_bridgesEvENKUlP9DexMethodE_clES1_ + 1168
6   redex-all                           0x0000000107ae764c _Z12walk_methodsINSt3__16vectorIP8DexClassNS0_9allocatorIS3_EEEEZN13BridgeRemover12find_bridgesEvEUlP9DexMethodE_EvRKT_T0_ + 140
7   redex-all                           0x0000000107ae71e4 _ZN13BridgeRemover3runEv + 20
8   redex-all                           0x0000000107ae7092 _ZN10BridgePass8run_passERNSt3__16vectorI10DexClassesNS0_9allocatorIS2_EEEER11ConfigFiles + 114
9   redex-all                           0x0000000107a9d488 _ZN11PassManager10run_passesERNSt3__16vectorI10DexClassesNS0_9allocatorIS2_EEEE + 408
10  redex-all                           0x0000000107a71228 main + 2168
11  libdyld.dylib                       0x00007fff9a6a85ad start + 1
Traceback (most recent call last):
  File "/usr/local/bin/redex", line 782, in <module>
    run_redex(args)
  File "/usr/local/bin/redex", line 738, in run_redex
    dexen)
  File "/usr/local/bin/redex", line 115, in run_pass
    subprocess.check_call(args, shell=True)
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/usr/local/bin/redex-all --apkdir /var/folders/7w/z7r6b_t13ds7_x65_4sjxwc80000gn/T/tmp97y47f8z.redex_extracted_apk --outdir /var/folders/7w/z7r6b_t13ds7_x65_4sjxwc80000gn/T/tmpmgpr1ph6.redex_dexen /var/folders/7w/z7r6b_t13ds7_x65_4sjxwc80000gn/T/tmpmgpr1ph6.redex_dexen/dex0/classes.dex' returned non-zero exit status -6

<<<<Context>>>>: 

Mac OS X version: 10.11.14
ues redex latest master branch

<<<Please Help>>>>

**Comment by shanenay** [comment] 2016-04-20 07:19
Duplicate of:
https://github.com/facebook/redex/issues/69

There's a temporary workaround in there while we figure out what's going sideways with bridge.

**Closed by shanenay** 2016-04-20 07:19 UTC
