### ISSUE TITLE
Android bundle support

### ISSUE THREAD

**Issue by kamalgsharma** [facebook/redex#638] opened 2021-09-10 02:35 UTC
Just wanted to check if we support Android bundle. I know this issue has been raised before, but wanted to check back again. Thanks.

**Comment by wsanville** [comment] 2021-09-10 04:37
Yes, basic support for .aab files does exist now in Redex with some limitations. Redex won't be able to process every conceivable .aab file that could exist though, and some limitations may exist indefinitely (for example, if an App Bundle has multiple conditional delivery feature modules with dex code that each define different versions of the same class, we're not going to handle this and will probably crash).

The installation instructions https://fbredex.com/docs/installation have been updated to reflect App Bundles, and the need for installing protobuf dependencies so that Redex can do things like read the AndroidManifest.xml from the bundle (which surprisingly is a protobuf message, not the compiled resources format for .apk files).

Other than the install setup, operating on .aab file should be pretty similar to operation on an .apk file, except don't pass in `--sign` to redex.py (bundletool should be signing for you, which you'll have to invoke manually after Redex) and make sure `--out` has the .aab file extension (default is .apk).

This stuff is pretty recent, so proper docs haven't been added yet, but yeah try it out and see what happens :)

**Comment by kamalgsharma** [comment] 2021-09-10 06:10
Thanks @wsanville , this is an awesome feature that you have built :) . I could generate an output bundle, but it seems that Redex rewrites some of the resource names as well, which causes a mismatch. Let me try to fix it locally and see if Redex produces a correct output.

**Comment by wsanville** [comment] 2021-09-10 14:39
> Redex rewrites some of the resource names as well, which causes a mismatch

I am a bit confused by this statement, of the open source passes I wasn't expecting any of them to be doing things like this. Can you provide some more details? In any case, it should be possible to turn off via a config most of the things that would be reading resources and editing them (i.e. renaming classes might be editing resources, btw).

Also, for debugging purposes to narrow this down, keep in mind that you can use `bundletool dump` to look at the resources before/after Redex runs.

**Comment by kamalgsharma** [comment] 2021-09-13 18:25
@wsanville , when I run with apk/aab, I see that there is modifications in the resources, even though I input an empty config. The error is as follows:
`bash-3.2$ bundletool build-apks --device-spec=/Users/kamal_sharma/Downloads/airbnb-aabFile/device-spec.json --bundle=output.aab --output=redex_app.apks
[BT:1.8.0] Error: Resource table of module 'dynamic_xyz' contains references to non-existing files: [res/raw/sB, res/raw/sA, res/raw/sF, res/raw/sG, res/raw/sD, res/raw/sE, res/raw/sC, res/raw/sJ, res/raw/sI, res/raw/sH, res/raw/sL, res/raw/sK, res/raw/sM, res/raw/sN, res/raw/sQ, res/raw/sO, res/raw/sP, res/raw/sV, res/raw/sT, res/raw/sU, res/raw/sS, res/raw/sR, res/raw/sX, res/raw/sZ, res/raw/sY, res/raw/sW]
com.android.tools.build.bundletool.model.exceptions.InvalidBundleException: Resource table of module 'dynamic_xyz' contains references to non-existing files: [res/raw/sB, res/raw/sA, res/raw/sF, res/raw/sG, res/raw/sD, res/raw/sE, res/raw/sC, res/raw/sJ, res/raw/sI, res/raw/sH, res/raw/sL, res/raw/sK, res/raw/sM, res/raw/sN, res/raw/sQ, res/raw/sO, res/raw/sP, res/raw/sV, res/raw/sT, res/raw/sU, res/raw/sS, res/raw/sR, res/raw/sX, res/raw/sZ, res/raw/sY, res/raw/sW]
	at com.android.tools.build.bundletool.model.exceptions.UserExceptionBuilder.build(UserExceptionBuilder.java:58)
	at com.android.tools.build.bundletool.validation.ResourceTableValidator.validateModule(ResourceTableValidator.java:101)
	at com.android.tools.build.bundletool.validation.ValidatorRunner.validateBundleModulesUsingSubValidator(ValidatorRunner.java:78)
	at com.android.tools.build.bundletool.validation.ValidatorRunner.validateBundleUsingSubValidator(ValidatorRunner.java:69)
	at com.android.tools.build.bundletool.validation.ValidatorRunner.lambda$validateBundle$3(ValidatorRunner.java:58)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:406)
	at com.android.tools.build.bundletool.validation.ValidatorRunner.validateBundle(ValidatorRunner.java:58)
	at com.android.tools.build.bundletool.validation.AppBundleValidator.validate(AppBundleValidator.java:106)
	at com.android.tools.build.bundletool.commands.BuildApksCommand.execute(BuildApksCommand.java:682)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:77)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:49)`

**Comment by kamalgsharma** [comment] 2021-09-13 18:27
It looks like Redex is rewriting many of the res/raw filenames, even though no optimization is specified.

**Comment by wsanville** [comment] 2021-09-14 00:30
> It looks like Redex is rewriting many of the res/raw filenames, even though no optimization is specified.

This is not something that should be happening when Redex runs (we don't do this to my knowledge). If you want help debugging further, please submit a complete example and command line invocation information so that we can easily reproduce this (you can start with the sample app bundle here https://github.com/facebook/redex/tree/master/test/samples/bundles and add some raw xml files in there to reproduce the issue).

**Comment by kamalgsharma** [comment] 2021-09-14 00:53
Let me see if there is a public apk version available.

**Comment by kamalgsharma** [comment] 2021-09-14 01:03
@wsanville , you can download a copy of the apk here: https://droidbang.com/link/airbnb-android ver 21.35.

Command used:
redex.py -c empty.config --android-sdk-path=/Users/kamal_sharma/Library/Android/sdk -o output.apk com.airbnb.android_21.35_24003757.apk --log-level debug

empty.config :
{
"redex" : {
  "passes" : [
  ]
}
}

The result output apk (res/raw) contains different xml filenames and files themselves.

**Comment by kamalgsharma** [comment] 2021-09-14 20:59
@wsanville , I was able to figure out the issue. It turns out that I was running redex on MacOS and by default filesystem is case insensitive. Thus, the unpacker was not able to distinguish between case sensitive files and overwriting them.
However, it turns out that even with no passes enabled, redex is still optimizing some of the dexes. I will post soon about how much is the increase.

**Comment by wsanville** [comment] 2021-09-15 02:16
Ah, filesystem differences. Yeah it makes sense that we wouldn't see this internally (not much use case for building on Mac), though feel free to either submit a patch for the unpacker logic, or a minimal example that illustrates the issue (like I mentioned before, a patch to this sample app https://github.com/facebook/redex/tree/master/test/samples/bundles to repro would be a good starting point).

Since at this point, the conversation has strayed pretty far from App Bundles support, I'll close this out; feel free to file separate issues for other problems encountered.

**Closed by wsanville** 2021-09-15 02:16 UTC
