### ISSUE TITLE
Unexpected field type in Kotlin

### ISSUE THREAD

**Issue by denis-trailin-hs** [facebook/redex#147] opened 2016-06-10 18:47 UTC
In my project with Kotlin I'm getting this issue when running redex:

```
opt/final_inline/FinalInline.cpp:208: bool validate_sget(DexMethod *, DexOpcodeField *): assertion 
false' failed.
Unexpected field type in inline_*sget sput-wide private static final double kotlin.jvm.internal.DoubleCompanionObject.MIN_VALUE v0 for field private static final double kotlin.jvm.internal.DoubleCompanionObject.MIN_VALUE value 1 in method private kotlin.jvm.internal.DoubleCompanionObject.<init>()V

0   redex-all                           0x00000001018b1d24 _Z15crash_backtracei + 52
1   libsystem_platform.dylib            0x00007fff9421652a _sigtramp + 26
2   ???                                 0x0000000000000000 0x0 + 0
3   libsystem_c.dylib                   0x00007fff9e09d6e7 abort + 129
4   redex-all                           0x00000001018b1ce1 _Z11assert_failPKcS0_jS0_S0_z + 177
5   redex-all                           0x0000000101922016 _ZL13validate_sgetP9DexMethodP14DexOpcodeField + 390
6   redex-all                           0x0000000101921cf9 _Z17inline_cheap_sgetP9DexMethodP14DexOpcodeField + 25
7   redex-all                           0x0000000101922c15 _Z19inline_field_valuesRNSt3__16vectorIP8DexClassNS_9allocatorIS2_EEEE + 1733
8   redex-all                           0x0000000101923070 _ZN15FinalInlinePass8run_passERNSt3__16vectorI10DexClassesNS0_9allocatorIS2_EEEER11ConfigFiles + 64
9   redex-all                           0x00000001018d10ea _ZN11PassManager10run_passesERNSt3__16vectorI10DexClassesNS0_9allocatorIS2_EEEER11ConfigFiles + 378
10  redex-all                           0x00000001018a3d77 main + 2263
11  libdyld.dylib                       0x00007fff979035ad start + 1
Traceback (most recent call last):
  File "./redex", line 788, in <module>
    run_redex(args)
  File "./redex", line 744, in run_redex
    dexen)
  File "./redex", line 115, in run_pass
    subprocess.check_call(args, shell=True)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 584, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command './redex-all --apkdir /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmpu8vur2fl.redex_extracted_apk --outdir /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex0/classes.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex1/classes2.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex2/classes3.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex3/classes4.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex4/classes5.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex5/classes6.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex6/classes7.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex7/classes8.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex8/classes9.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex9/classes10.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex10/classes11.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex11/classes12.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex12/classes13.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex13/classes14.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex14/classes15.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex15/classes16.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex16/classes17.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex17/classes18.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex18/classes19.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex19/classes20.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex20/classes21.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex21/classes22.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex22/classes23.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex23/classes24.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex24/classes25.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex25/classes26.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex26/classes27.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex27/classes28.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex28/classes29.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex29/classes30.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex30/classes31.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex31/classes32.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex32/classes33.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex33/classes34.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex34/classes35.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex35/classes36.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex36/classes37.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex37/classes38.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex38/classes39.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex39/classes40.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex40/classes41.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex41/classes42.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex42/classes43.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex43/classes44.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex44/classes45.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex45/classes46.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex46/classes47.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex47/classes48.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex48/classes49.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex49/classes50.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex50/classes51.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex51/classes52.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex52/classes53.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex53/classes54.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex54/classes55.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex55/classes56.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex56/classes57.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex57/classes58.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex58/classes59.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex59/classes60.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex60/classes61.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex61/classes62.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex62/classes63.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex63/classes64.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex64/classes65.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex65/classes66.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex66/classes67.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex67/classes68.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex68/classes69.dex /var/folders/hp/0033ls7n1_zg72twy3j5wlcm0000gq/T/tmppu946cts.redex_dexen/dex69/classes70.dex' returned non-zero exit status -6
```

**Comment by liufsd** [comment] 2016-06-13 11:37
```
opt/final_inline/FinalInline.cpp:141: bool validate_sget(DexMethod *, DexOpcodeField *): assertion `false' failed.
Unexpected field type in inline_*sget sput private static final int com.hujiang.normandy.app.lesson.utils.LessonCompleteHelper.ˎ v0 for field private static final int com.hujiang.normandy.app.lesson.utils.LessonCompleteHelper.ˎ value 3 in method private com.hujiang.normandy.app.lesson.utils.LessonCompleteHelper.<init>()V

0   redex-all                           0x0000000108123a24 _Z15crash_backtracei + 52
1   libsystem_platform.dylib            0x00007fff95c0152a _sigtramp + 26
2   ???                                 0x0000000000000000 0x0 + 0
3   libsystem_c.dylib                   0x00007fff9e44d6e7 abort + 129
4   redex-all                           0x00000001081239e1 _Z11assert_failPKcS0_jS0_S0_z + 177
5   redex-all                           0x00000001081985d6 _ZL13validate_sgetP9DexMethodP14DexOpcodeField + 390
6   redex-all                           0x00000001081982b9 _Z17inline_cheap_sgetP9DexMethodP14DexOpcodeField + 25
7   redex-all                           0x00000001081991d5 _Z19inline_field_valuesRNSt3__16vectorIP8DexClassNS_9allocatorIS2_EEEE + 1733
8   redex-all                           0x0000000108199612 _ZN15FinalInlinePass8run_passERNSt3__16vectorI10DexClassesNS0_9allocatorIS2_EEEER11ConfigFiles + 34
9   redex-all                           0x00000001081445aa _ZN11PassManager10run_passesERNSt3__16vectorI10DexClassesNS0_9allocatorIS2_EEEER11ConfigFiles + 378
10  redex-all                           0x0000000108119281 main + 2705
11  libdyld.dylib                       0x00007fff8ad7d5ad start + 1
12  ???                                 0x0000000000000007 0x0 + 7
Traceback (most recent call last):
  File "/usr/local/bin/redex", line 797, in <module>
    run_redex(args)
  File "/usr/local/bin/redex", line 752, in run_redex
    dexen)
  File "/usr/local/bin/redex", line 114, in run_pass
    subprocess.check_call(args, shell=True)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 584, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/usr/local/bin/redex-all --apkdir /var/folders/6b/s7fpkh617lx3thn0xwhrvtbr0000gp/T/tmp56casjto.redex_extracted_apk --outdir /var/folders/6b/s7fpkh617lx3thn0xwhrvtbr0000gp/T/tmpw7n8khn1.redex_dexen /var/folders/6b/s7fpkh617lx3thn0xwhrvtbr0000gp/T/tmpw7n8khn1.redex_dexen/dex0/classes.dex /var/folders/6b/s7fpkh617lx3thn0xwhrvtbr0000gp/T/tmpw7n8khn1.redex_dexen/dex1/classes2.dex' returned non-zero exit status -6
```

**Comment by justinjhendrick** [comment] 2017-06-26 23:54
closing due to age. If you still see this error on the newest version, please re-open or create new issue.

**Closed by justinjhendrick** 2017-06-26 23:54 UTC

**Comment by justinjhendrick** [comment] 2017-07-24 21:34
duplicate of #126
