### ISSUE TITLE
Assert error on the Triada malware

### ISSUE THREAD

**Issue by romainthomas** [facebook/redex#216] opened 2017-05-17 14:36 UTC
Trying to use redex on a obfuscated malware ([Triada](https://koodous.com/apks/ba1d6f317214d318b2a4e9a9663bc7ec867a6c845affecad1290fd717cc74f29) - ``ba1d6f317214d318b2a4e9a9663bc7ec867a6c845affecad1290fd717cc74f29``).

I get this error: (with the ``PrintMembersPass`` pass)
```bash
$ ./redex triada.apk
libredex/Transform.cpp:2264: bool IRCode::try_sync(DexCode *): assertion `active_try == nullptr' failed.
libredex/Transform.cpp:2264: bool IRCode::try_sync(DexCode *): assertion `active_try == nullptr' failed.
....
Failed to sync Lcom/android/system/admin/OcooIclc;.oCOllOO:()Z
```

**Comment by justinjhendrick** [comment] 2017-05-17 17:12
Could I see your `.config` file please? Which redex commit are you based on?

cc @int3. hg blame show you touched these lines last.

**Comment by justinjhendrick** [comment] 2017-05-17 17:16
Also, could we see the full stack trace, please?

**Comment by romainthomas** [comment] 2017-05-17 17:42
I'm based on the commit d9d5c53. Here is the ``config``:

```
{
  "redex" : {
    "passes" : [
      "PrintMembersPass"
    ]
  }
}
```

And the full dump is available here: https://pastebin.com/uBxHa38q

**Comment by justinjhendrick** [comment] 2017-05-17 18:05
hmmm... That stack trace isn't very legible, haha

Let's see if we can get debug symbols.

edit https://github.com/facebook/redex/blob/master/Makefile.am#L6 to be
```
AM_CXXFLAGS = --std=gnu++11 -O0 -Wall -g
```
then re-build redex and try again
```
$ autoreconf -ivf && ./configure && make
$ sudo make install
$ ./redex triada.apk
```
Then please paste the stack again :)

**Comment by romainthomas** [comment] 2017-05-17 18:34
The ``-O0`` flag doesn't change the output so I provide the backtrace from gdb:

```
#0  0x00007ffff6417a10 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff641913a in abort () from /usr/lib/libc.so.6
#2  0x00007ffff6d434ed in __gnu_cxx::__verbose_terminate_handler () at /build/gcc-multilib/src/gcc/libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x00007ffff6d412a6 in __cxxabiv1::__terminate (handler=<optimized out>) at /build/gcc-multilib/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:47
#4  0x00007ffff6d412f1 in std::terminate () at /build/gcc-multilib/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:57
#5  0x00007ffff6d41556 in __cxxabiv1::__cxa_rethrow () at /build/gcc-multilib/src/gcc/libstdc++-v3/libsupc++/eh_throw.cc:125
#6  0x0000000000547bad in IRCode::sync (this=<optimized out>, method=<optimized out>) at libredex/Transform.cpp:2102
#7  0x00000000004ca58d in DexMethod::sync (this=0x7fffe40a8a40) at libredex/DexClass.cpp:446
#8  0x00000000005578ed in WorkQueue::worker_thread (priv=0x815520) at libredex/WorkQueue.cpp:73
#9  0x00007ffff74902e7 in start_thread () from /usr/lib/libpthread.so.0
#10 0x00007ffff64d054f in clone () from /usr/lib/libc.so.6
```

**Comment by justinjhendrick** [comment] 2017-05-17 18:57
It looks like redex is having issues with a nested try... but I can't repro it with this

```
      try {
        if (Math.random() > .5) {
          throw new Exception1();
        }
        try {
          if (Math.random() > .5) {
            throw new Exception2();
          }
        } catch (Exception2 e) {
          System.out.println(e.toString());
        }
      } catch (Exception1 e) {
        System.out.println(e.toString());
      }
```

Do you have the source code to this app?

**Comment by romainthomas** [comment] 2017-05-17 19:05
Sorry I don't but you can download it here: http://romainthomas.fr/triada.apk

**Comment by justinjhendrick** [comment] 2017-05-17 21:13
Okay, I've reproduced it and I'm debugging now

**Comment by justinjhendrick** [comment] 2017-05-18 00:12
I have a fix. It was a rather subtle bug! Thanks for bringing it to our attention :)

**Comment by justinjhendrick** [comment] 2017-05-18 00:13
Do you want me to send you a patch now? Or do you mind waiting for a day or so for it to go through our code review & tests?

**Comment by justinjhendrick** [comment] 2017-05-18 04:29
The fix should be on master in a few hours. Closing this issue.

**Comment by romainthomas** [comment] 2017-05-18 06:09
Thank you!

**Closed** 2017-05-18 14:34 UTC
