### ISSUE TITLE
configure error: Please Install double-conversion library

### ISSUE THREAD

**Issue by pawelkw** [facebook/redex#29] opened 2016-04-13 09:57 UTC
```
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force 
autoreconf: configure.ac: tracing
autoreconf: configure.ac: adding subdirectory third-party/folly/folly to autoreconf
autoreconf: Entering directory `third-party/folly/folly'
autoreconf: running: aclocal --force -I m4
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `build-aux'.
libtoolize: copying file `build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
autoreconf: Leaving directory `third-party/folly/folly'
autoreconf: configure.ac: not using Libtool
configure.ac:6: warning: AM_INIT_AUTOMAKE: two- and three-arguments forms are deprecated.  For more info, see:
configure.ac:6: http://www.gnu.org/software/automake/manual/automake.html#Modernize-AM_005fINIT_005fAUTOMAKE-invocation
autoreconf: Leaving directory `.'
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for style of include used by make... GNU
checking dependency style of g++... gcc3
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for ranlib... ranlib
checking dependency style of gcc... (cached) gcc3
checking dependency style of g++... (cached) gcc3
checking for a Python interpreter with version >= 3.0... python3
checking for python3... /usr/bin/python3
checking for python3 version... 3.4
checking for python3 platform... linux
checking for python3 script directory... ${prefix}/lib/python3.4/site-packages
checking for python3 extension module directory... ${exec_prefix}/lib/python3.4/site-packages
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for boostlib >= 1.54.0... yes
checking whether the Boost::Filesystem library is available... yes
checking for exit in -lboost_filesystem... yes
checking whether the Boost::System library is available... yes
checking for exit in -lboost_system... yes
checking for adler32 in -lz... yes
checking for ceil in -ldouble-conversion... no
configure: error: Please install double-conversion library

```

Followed the readme. All dependencies installed correctly. Ubuntu 14.04.

**Comment by bastian-meier** [comment] 2016-04-13 10:57
I am facing the same Issue

**Comment by herberthamaral** [comment] 2016-04-13 10:58
Tried to remove Ubuntu's double-conversion and install it manually via source (https://github.com/google/double-conversion) but the problem was not solved. I suspect the problem lies within the configure script but I do not have sufficient knowledge to fix or even confirm that :(

**Comment by the4thfloor** [comment] 2016-04-13 12:21
take a look at https://github.com/facebook/redex/issues/15

**Comment by marcosdiez** [comment] 2016-04-13 13:59
Just for the record, here ( Ubuntu ), I had this error fixed after typing
git revert 2a1b9609f48ebd64def6260e2018b3d476c2d9f0

**Comment by bertmaher** [comment] 2016-04-13 17:39
Duplicate of #15

**Closed by bertmaher** 2016-04-13 17:39 UTC

**Comment by marcosdiez** [comment] 2016-04-13 17:49
@bertmaher I belive this issue should not be closed. At least on Ubuntu, unless one does the git revert I suggested, one can't compile it.
```
git revert 2a1b9609f48ebd64def6260e2018b3d476c2d9f0
```
