### ISSUE TITLE
Could not launch app. 

### ISSUE THREAD

**Issue by sunada-ke** [facebook/redex#64] opened 2016-04-14 13:00 UTC
I used redex with the following process, I created a optimized apk file.
-  I've created a apk file in Android Studio by Mac OS. (Using proguard.)
- I establish the environment on Ubuntu, and I ran the following command on Ubuntu.

```
redex xxx.apk  -o output.apk --sign -s xxxKeystore -a xxx -p xxx
```
-  I ran the following command on Mac.

```
adb install output.apk
```

Then, when you launch the app, app crashed.
This is crash log.

```
Shutting down VM
04-14 21:41:22.725 W/dalvikvm(16840): threadid=1: thread exiting with uncaught exception (group=0x417fb450)
04-14 21:41:22.735 E/AndroidRuntime(16840): FATAL EXCEPTION: main
04-14 21:41:22.735 E/AndroidRuntime(16840): java.lang.ExceptionInInitializerError
04-14 21:41:22.735 E/AndroidRuntime(16840):     at org.xbill.DNS.TTL.addIQProvider(subscription_depth:14)
04-14 21:41:22.735 E/AndroidRuntime(16840):     at com.xxx.App.onCreate(updateIndicator:24)
04-14 21:41:22.735 E/AndroidRuntime(16840):     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:999)
04-14 21:41:22.735 E/AndroidRuntime(16840):     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4192)
04-14 21:41:22.735 E/AndroidRuntime(16840):     at android.app.ActivityThread.access$1300(ActivityThread.java:137)
04-14 21:41:22.735 E/AndroidRuntime(16840):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1266)
04-14 21:41:22.735 E/AndroidRuntime(16840):     at android.os.Handler.dispatchMessage(Handler.java:99)
04-14 21:41:22.735 E/AndroidRuntime(16840):     at android.os.Looper.loop(Looper.java:213)
04-14 21:41:22.735 E/AndroidRuntime(16840):     at android.app.ActivityThread.main(ActivityThread.java:4786)
04-14 21:41:22.735 E/AndroidRuntime(16840):     at java.lang.reflect.Method.invokeNative(Native Method)
04-14 21:41:22.735 E/AndroidRuntime(16840):     at java.lang.reflect.Method.invoke(Method.java:511)
04-14 21:41:22.735 E/AndroidRuntime(16840):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
04-14 21:41:22.735 E/AndroidRuntime(16840):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
04-14 21:41:22.735 E/AndroidRuntime(16840):     at dalvik.system.NativeStart.main(Native Method)
04-14 21:41:22.735 E/AndroidRuntime(16840): Caused by: java.lang.ExceptionInInitializerError
04-14 21:41:22.735 E/AndroidRuntime(16840):     at org.jivesoftware.smack.provider.ProviderManager.<clinit>(timeoutInMillis:121)
04-14 21:41:22.735 E/AndroidRuntime(16840):     ... 14 more
04-14 21:41:22.735 E/AndroidRuntime(16840): Caused by: java.lang.NoSuchMethodError: org.jivesoftware.smack.provider.IQProviderInfo.getElementName
04-14 21:41:22.735 E/AndroidRuntime(16840):     at org.jivesoftware.smack.provider.ProviderManager.addLoader(timeoutInMillis:128)
04-14 21:41:22.735 E/AndroidRuntime(16840):     at org.jivesoftware.smack.initializer.UrlInitializer.initialize(startAlpha:54)
04-14 21:41:22.735 E/AndroidRuntime(16840):     at org.jivesoftware.smack.SmackInitialization.loadSmackClass(titleRes:232)
04-14 21:41:22.735 E/AndroidRuntime(16840):     at org.jivesoftware.smack.SmackInitialization.parseClassesToLoad(titleRes:193)
04-14 21:41:22.735 E/AndroidRuntime(16840):     at org.jivesoftware.smack.SmackInitialization.processConfigFile(titleRes:163)
04-14 21:41:22.735 E/AndroidRuntime(16840):     at org.jivesoftware.smack.SmackInitialization.processConfigFile(titleRes:148)
04-14 21:41:22.735 E/AndroidRuntime(16840):     at org.jivesoftware.smack.SmackInitialization.<clinit>(titleRes:116)
04-14 21:41:22.735 E/AndroidRuntime(16840):     ... 15 more
```

I don't know what happened.

Perhaps, it have been optimized external jar by redex? I have been excluded external jar by the setting of proguard. 
When I create a apk file,  do not use the proguard?

**Comment by VenomVendor** [comment] 2016-04-19 02:54
Duplicate of #30

**Comment by justinjhendrick** [comment] 2017-06-26 23:45
closing due to age

**Closed by justinjhendrick** 2017-06-26 23:45 UTC
