### ISSUE TITLE
redex-all crashed with exit code -11

### ISSUE THREAD

**Issue by xnfreedom** [facebook/redex#462] opened 2020-03-03 08:43 UTC
Use code version: 51fb0021e07
Error info:
WARNING: Unable to find RequiresApi annotation. It's either unused (okay) or been deleted (not okay)
WARNING: No inliner config
ABORT! Inconsistency found in Dex code for Lgnu/crypto/hash/Haval;.transform:([BI)V.
 Type error in method Lgnu/crypto/hash/Haval;.transform:([BI)V at instruction 'AGET_BYTE v0, v0' @ 0x7f7904cbe0c0 for register v0: expected type INT, but found REFERENCE instead
Code:
.....
--------------------
The APK compiled with Android gradle.

**Comment by agampe** [comment] 2020-03-03 16:26
Duplicate of #458

**Comment by justinjhendrick** [comment] 2020-03-03 19:57
Closing as duplicate

**Closed by justinjhendrick** 2020-03-03 19:57 UTC
