### ISSUE TITLE
tools/hprof/dump_classes_from_hprof.py   error

### ISSUE THREAD

**Issue by LPhoenix365** [facebook/redex#569] opened 2020-11-26 08:11 UTC
i try this:
```
python3 tools/hprof/dump_classes_from_hprof.py --hprof /Users/Downloads/load.hprof  > list_of_classes.txt
```

however:

```
Traceback (most recent call last):
  File "tools/hprof/dump_classes_from_hprof.py", line 1459, in <module>
    hp = parse_filename(args.hprof)
  File "tools/hprof/dump_classes_from_hprof.py", line 68, in parse_filename
    return parse_hprof_dump(open(filename, "rb"))
  File "tools/hprof/dump_classes_from_hprof.py", line 58, in parse_hprof_dump
    hprof_data.resolve()
  File "tools/hprof/dump_classes_from_hprof.py", line 969, in resolve
    clazz.resolve(self)
  File "tools/hprof/dump_classes_from_hprof.py", line 618, in resolve
    assert name not in self.fields.__dict__
AssertionError
```

What shall I do? Anyone else

**Comment by amnn** [comment] 2020-11-26 11:45
It is difficult to tell exactly what is going on, but by looking at the code responsible for throwing the error

https://github.com/facebook/redex/blob/d242f017ea9332da0b4e1dc322e68477705ae0a0/tools/hprof/dump_classes_from_hprof.py#L615-L619

it looks like the hprof contains a class with static fields whose names are duplicated *and* collide with the name of a python field.    The main issue is that the field name is duplicated in the class -- this should not happen in a well-formed hprof (because classes cannot have static fields whose names shadow each other).

This tool only supports Android 4 and below (Android versions using Dalvik runtimes), due to technical issues in hprofs from later versions (see https://github.com/facebook/redex/issues/529#issuecomment-674984041.) This may be an example of that -- let us know if the hprof was generated from a later version of Android.

**Comment by LPhoenix365** [comment] 2020-11-27 12:27
okay,thank you for your prompt reply, but I still have the same problem using Dalvik virtual machine,and i no time to explore now

**Comment by LPhoenix365** [comment] 2020-11-27 12:29
but I still want to try redex

**Comment by amnn** [comment] 2020-11-27 12:31
If you are able to provide a minimal hprof that still exhibits the problem, we can try and reproduce the error and investigate it.

**Comment by LPhoenix365** [comment] 2020-11-27 12:48
[SOMEDUMP.hprof.zip](https://github.com/facebook/redex/files/5607888/SOMEDUMP.hprof.zip)

**Comment by amnn** [comment] 2020-11-27 18:20
In that heap profile, static fields in classes from the `com.xiaomi.*` namespaces have conflicting field names.  I was able to confirm what the script was seeing for `com.xiaomi.mipush.sdk.aw`, using a heap profiler (I used YourKit 2019, but Eclipse MAT should show the same), which has two static fields, both named `a`, but of different types.  This could be because the SDK they come from is obfuscated to prevent people from accessing those fields.

As `dump_classes_from_hprof` is not designed to work in that scenario, I'm going to close this issue -- the right step is to make sure the names in the input make sense.  I will say that the script produced an output when the assertion (on L618) was commented out, but this effectively allows the script to overwrite fields with the same name, so could have unintended consequences -- use with caution!

**Closed by amnn** 2020-11-27 18:20 UTC
