### ISSUE TITLE
./../folly/portability/Malloc.h:27:12: error: unknown type name 'size_t' extern "C" size_t malloc_usable_size(void* ptr);

### ISSUE THREAD

**Issue by jaredsburrows** [facebook/redex#43] opened 2016-04-13 16:38 UTC
Using MacOSX:

OS X Yosemite
Version 10.10.5
Xcodebuild tools: Xcode 7.0.1
Build version 7A1001

Step 1:

```
brew install autoconf automake libtool
brew install boost double-conversion gflags glog libevent
```

Step 2:

```
git clone "https://github.com/facebook/redex.git"
cd "redex"
```

Step 3:

```
git submodule update --init
```

Step 4:
```
autoreconf -ivf && ./configure && make && make install
```
This needs python3, so you need to do `brew install python3`.

This step leads to a build failure:

```
	mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  g++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/local/include -std=gnu++0x -g -O2 -MT portability/Malloc.lo -MD -MP -MF portability/.deps/Malloc.Tpo -c portability/Malloc.cpp  -fno-common -DPIC -o portability/.libs/Malloc.o
In file included from portability/Malloc.cpp:17:
./../folly/portability/Malloc.h:27:12: error: unknown type name 'size_t'
extern "C" size_t malloc_usable_size(void* ptr);
           ^
1 error generated.
make[4]: *** [portability/Malloc.lo] Error 1
make[3]: *** [all-recursive] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

This is why a prebuilt lib for MacOSX via Homebrew would be nice: https://github.com/facebook/redex/issues/41.

**Comment by jrodbx** [comment] 2016-04-13 16:59
this appears to be a duplicate of https://github.com/facebook/redex/issues/8

**Comment by bertmaher** [comment] 2016-04-13 17:41
Thanks, will have the fix landed when I update folly later today.

**Closed by bertmaher** 2016-04-13 17:41 UTC

**Comment by StevenTB** [comment] 2016-05-03 06:54
When I tried to install double-conversion and libevent I had two issues ;
- there is no available formula for double-conversion
- libevent library hosted in sourceforge leads to a 404.

To avoid this, I support @jaredsburrows to say that it would be very nice to add redex to Homebrew
