### ISSUE TITLE
Parse Error when installing the redex output apk

### ISSUE THREAD

**Issue by shreyjade** [facebook/redex#87] opened 2016-04-18 05:55 UTC
When i created the output apk using redex tool, parse error was coming when installing the apk. 
"There was a problem while parsing the package." Please guide how to fix it.

**Comment by chiemy** [comment] 2016-04-18 08:20
same problem

**Comment by huyongli** [comment] 2016-04-18 09:44
resign the apk is ok

**Comment by VenomVendor** [comment] 2016-04-19 02:58
Duplicate of #23

**Closed** 2016-04-19 04:31 UTC
