### ISSUE TITLE
crash when launch app

### ISSUE THREAD

**Issue by huyongli** [facebook/redex#96] opened 2016-04-18 11:19 UTC
I've created a apk file in Android Studio by ubuntu 14.0.1 LTS. (Using proguard.)
When I launch the redex apk，it's crash.
This is the exception.

`java.lang.IllegalAccessError: tried to access class io.fabric.sdk.android.services.common.ExecutorUtils$1 from class uk.co.senab.photoview.gestures.VersionedGestureDetector
                                                                      at uk.co.senab.photoview.gestures.VersionedGestureDetector.getNamedThreadFactory(sync:68)
                                                                      at com.crashlytics.android.core.CrashlyticsCore.<init>(while open={} more={} progress={}:42)
                                                                      at com.crashlytics.android.core.CrashlyticsCore.<init>(while open={} more={} progress={}:200)
                                                                      at com.crashlytics.android.Crashlytics.<init>(wireType:29)
                                                                      at cn.ittiger.NewsApplication.initSdks(uk:25)
                                                                      at cn.ittiger.NewsApplication.onCreate(uk:66)
                                                                      at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1069)
                                                                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4647)
                                                                      at android.app.ActivityThread.access$1300(ActivityThread.java:168)
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1436)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                      at android.os.Looper.loop(Looper.java:194)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5398)
                                                                      at java.lang.reflect.Method.invokeNative(Native Method)
                                                                      at java.lang.reflect.Method.invoke(Method.java:525)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:836)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:603)
                                                                      at dalvik.system.NativeStart.main(Native Method)`

I don't know the reason, my project use proguard.

Can I  use proguard when I create APK ?

**Comment by VenomVendor** [comment] 2016-04-19 02:52
Duplicate of #30

**Closed** 2016-04-20 00:46 UTC
